# See https://pre-commit.com/ for usage and config
repos:
- repo: https://github.com/markdownlint/markdownlint
  rev: v0.11.0
  hooks:
  - id: markdownlint
    name: markdownlint
    stages: [commit]
    language: ruby
    entry: mdl
    types: [markdown]
- repo: https://github.com/bcbernardo/mirrors-lmt
  rev: 9e94377dcec039541d5bec7e9ba73056078ab435
  hooks:
  - id: lmt
    name: lmt
    stages: [commit]
    language: golang
    entry: lmt
    files: HOWTO.md
- repo: local
  hooks:
  - id: isort
    name: isort
    stages: [commit]
    language: system
    entry: poetry run isort
    types: [python]

  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black
    args: [--line-length=79]
    types: [python]

  - id: pylint
    name: pylint
    stages: [commit]
    language: system
    entry: poetry run pylint
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: poetry run mypy
    types: [python]
    require_serial: true

  - id: pytest
    name: pytest
    stages: [commit]
    language: system
    entry: poetry run pytest
    types: [python]
    pass_filenames: false